import backendApiClient from '../utils/apiClient.js';
import usersService from './usersService.js';

//Generated by copilot edits; Attaching the oas files and one example fucntion.


/**
 * Create a new itinerary.
 * @param {Object} data - The itinerary data.
 * @returns {Promise<Object>} The created itinerary.
 */
export const createItinerary = async (data) => {
  console.log('%c[createItinerary] Request data:', 'color: blue;', data);
  const response = await backendApiClient.post('/itineraries/api/v1/itineraries', data);
  console.log('%c[createItinerary] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get all itineraries.
 * @returns {Promise<Array>} A list of itineraries.
 */
export const getAllItineraries = async () => {
  console.log('%c[getAllItineraries] Requesting all itineraries', 'color: blue;');
  const response = await backendApiClient.get('/itineraries/api/v1/itineraries');
  console.log('%c[getAllItineraries] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get a specific itinerary by ID.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<Object>} The requested itinerary.
 */
export const getItineraryById = async (itineraryId) => {
  console.log('%c[getItineraryById] Requesting itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}`);
  console.log('%c[getItineraryById] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Update an existing itinerary by ID.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {Object} data - The updated itinerary data.
 * @returns {Promise<Object>} The updated itinerary.
 */
export const updateItineraryById = async (itineraryId, data) => {
  console.log('%c[updateItineraryById] Updating itinerary with ID:', 'color: blue;', itineraryId, 'and data:', data);
  const response = await backendApiClient.put(`/itineraries/api/v1/itineraries/${itineraryId}`, data);
  console.log('%c[updateItineraryById] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Delete an itinerary by ID.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<void>} No content.
 */
export const deleteItineraryById = async (itineraryId) => {
  console.log('%c[deleteItineraryById] Deleting itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.delete(`/itineraries/api/v1/itineraries/${itineraryId}`);
  console.log('%c[deleteItineraryById] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Add a new activity to an itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {Object} data - The activity data.
 * @returns {Promise<Object>} The added activity.
 */
export const addActivityToItinerary = async (itineraryId, data) => {
  console.log('%c[addActivityToItinerary] Adding activity to itinerary with ID:', 'color: blue;', itineraryId, 'and data:', data);
  const response = await backendApiClient.post(`/itineraries/api/v1/itineraries/${itineraryId}/activities`, data);
  console.log('%c[addActivityToItinerary] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get all activities for a specific itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<Array>} A list of activities.
 */
export const getActivitiesByItineraryId = async (itineraryId) => {
  console.log('%c[getActivitiesByItineraryId] Requesting activities for itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/activities`);
  console.log('%c[getActivitiesByItineraryId] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get a specific activity by index.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {number} activityIndex - The index of the activity.
 * @returns {Promise<Object>} The requested activity.
 */
export const getActivityByIndex = async (itineraryId, activityIndex) => {
  console.log('%c[getActivityByIndex] Requesting activity with index:', 'color: blue;', activityIndex, 'from itinerary with ID:', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/activities/${activityIndex}`);
  console.log('%c[getActivityByIndex] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get the weather forecast for a specific activity.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {number} activityIndex - The index of the activity.
 * @returns {Promise<Object>} The weather forecast for the activity.
 */
export const getActivityForecast = async (itineraryId, activityIndex) => {
  console.log('%c[getActivityForecast] Requesting weather forecast for activity with index:', 'color: blue;', activityIndex, 'from itinerary with ID:', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/activities/${activityIndex}/forecast`);
  console.log('%c[getActivityForecast] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Delete an activity by index.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {number} activityIndex - The index of the activity.
 * @returns {Promise<void>} No content.
 */
export const deleteActivityByIndex = async (itineraryId, activityIndex) => {
  console.log('%c[deleteActivityByIndex] Deleting activity with index:', 'color: blue;', activityIndex, 'from itinerary with ID:', itineraryId);
  const response = await backendApiClient.delete(`/itineraries/api/v1/itineraries/${itineraryId}/activities/${activityIndex}`);
  console.log('%c[deleteActivityByIndex] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Submit a comment for an itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {Object} data - The comment data.
 * @returns {Promise<Object>} The added comment.
 */
export const submitCommentForItinerary = async (itineraryId, data) => {
  console.log('%c[submitCommentForItinerary] Submitting comment for itinerary with ID:', 'color: blue;', itineraryId, 'and data:', data);
  const response = await backendApiClient.post(`/itineraries/api/v1/itineraries/${itineraryId}/comments`, data);
  console.log('%c[submitCommentForItinerary] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get all comments for a specific itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<Array>} A list of comments.
 */
export const getCommentsByItineraryId = async (itineraryId) => {
  console.log('%c[getCommentsByItineraryId] Requesting comments for itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/comments`);
  console.log('%c[getCommentsByItineraryId] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Delete a comment by ID.
 * @param {string} commentId - The ID of the comment.
 * @returns {Promise<void>} No content.
 */
export const deleteCommentById = async (commentId) => {
  console.log('%c[deleteCommentById] Deleting comment with ID:', 'color: blue;', commentId);
  const response = await backendApiClient.delete(`/v1/comments/${commentId}`);
  console.log('%c[deleteCommentById] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Submit a review for an itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @param {Object} data - The review data.
 * @returns {Promise<Object>} The added review.
 */
export const submitReviewForItinerary = async (itineraryId, data) => {
  console.log('%c[submitReviewForItinerary] Submitting review for itinerary with ID:', 'color: blue;', itineraryId, 'and data:', data);
  const response = await backendApiClient.post(`/itineraries/api/v1/itineraries/${itineraryId}/reviews`, data);
  console.log('%c[submitReviewForItinerary] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get all reviews for a specific itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<Array>} A list of reviews.
 */
export const getReviewsByItineraryId = async (itineraryId) => {
  console.log('%c[getReviewsByItineraryId] Requesting reviews for itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/reviews`);
  console.log('%c[getReviewsByItineraryId] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Get the average review score for a specific itinerary.
 * @param {string} itineraryId - The ID of the itinerary.
 * @returns {Promise<Object>} The average review score.
 */
export const getAverageReviewScoreByItineraryId = async (itineraryId) => {
  console.log('%c[getAverageReviewScoreByItineraryId] Requesting average review score for itinerary with ID:', 'color: blue;', itineraryId);
  const response = await backendApiClient.get(`/itineraries/api/v1/itineraries/${itineraryId}/average-reviews-score`);
  console.log('%c[getAverageReviewScoreByItineraryId] Response:', 'color: green;', response);
  return response.data?.data;
};

/**
 * Delete a review by ID.
 * @param {string} reviewId - The ID of the review.
 * @returns {Promise<void>} No content.
 */
export const deleteReviewById = async (reviewId) => {
  console.log('%c[deleteReviewById] Deleting review with ID:', 'color: blue;', reviewId);
  const response = await backendApiClient.delete(`/v1/reviews/${reviewId}`);
  console.log('%c[deleteReviewById] Response:', 'color: green;', response);
  return response.data?.data;
};

export default {
  getAllItineraries,
  createItinerary,
  getItineraryById,
  updateItineraryById,
  deleteItineraryById,

  addActivityToItinerary,
  getActivitiesByItineraryId,
  getActivityByIndex,
  getActivityForecast,
  deleteActivityByIndex,

  submitCommentForItinerary,
  getCommentsByItineraryId,
  deleteCommentById,

  submitReviewForItinerary,
  getReviewsByItineraryId,
  getAverageReviewScoreByItineraryId,
  deleteReviewById,

  TEST_ALL,
};

async function TEST_ALL(realUser = false) {
  let user;
  if (realUser) {
    console.log('USING REAL USER:');
    // Create a new itinerary
    user = usersService.getLoggedUser();
  } else {
    console.log('USING MOCK USER1:');
    user = await usersService.postLogin({ userId: "user1", password: "password1" });
  }
  const newItinerary = {
    name: 'Vacation in Hawaii',
    description: 'A relaxing vacation in Hawaii',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    activities: [],
    comments: [],
    reviews: []
  };

  const newActivity = {
    userId: user._id,
    name: 'Snorkeling',
    description: 'Snorkeling in the coral reefs',
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // 1 day from now
    endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000), // 2 hours duration
    location: {
      latitude: 21.3069,
      longitude: -157.8583,
      address: 'Waikiki Beach, Honolulu, HI'
    }
  };

  const createdItinerary = await createItinerary(newItinerary);
  console.log('Created Itinerary:', createdItinerary);
  // Get all itineraries
  const allItineraries = await getAllItineraries();
  console.log('All Itineraries:', allItineraries);

  // Get a specific itinerary by ID
  const itineraryId = createdItinerary._id;
  const itinerary = await getItineraryById(itineraryId);
  console.log('Itinerary by ID:', itinerary);

  // Update the itinerary
  const updatedData = { name: 'Updated Vacation in Hawaii2', ...createdItinerary };
  const updatedItinerary = await updateItineraryById(itineraryId, updatedData);
  console.log('Updated Itinerary:', updatedItinerary);

  // Add an activity to the itinerary

  const addedActivity = await addActivityToItinerary(itineraryId, newActivity);
  console.log('Added Activity:', addedActivity);

  // Get all activities for the itinerary
  const activities = await getActivitiesByItineraryId(itineraryId);
  console.log('Activities:', activities);

  // Get a specific activity by index
  const activityIndex = 0;
  const activity = await getActivityByIndex(itineraryId, activityIndex);
  console.log('Activity by Index:', activity);

  // Get the weather forecast for the activity
  const activityForecast = await getActivityForecast(itineraryId, activityIndex);
  console.log('Activity Forecast:', activityForecast);

  // Submit a comment for the itinerary
  const newComment = { title: 'This looks amazing!', message: 'This looks amazing!' };
  const addedComment = await submitCommentForItinerary(itineraryId, newComment);
  console.log('Added Comment:', addedComment);

  // Get all comments for the itinerary
  const comments = await getCommentsByItineraryId(itineraryId);
  console.log('Comments:', comments);

  // Submit a review for the itinerary
  const newReview = { score: 5, title: 'Best vacation ever!', message: 'Best vacation ever!' };
  const addedReview = await submitReviewForItinerary(itineraryId, newReview);
  console.log('Added Review:', addedReview);

  // Get all reviews for the itinerary
  const reviews = await getReviewsByItineraryId(itineraryId);
  console.log('Reviews:', reviews);

  // Get the average review score for the itinerary
  const averageReviewScore = await getAverageReviewScoreByItineraryId(itineraryId);
  console.log('Average Review Score:', averageReviewScore);

  // Delete the itinerary
  await deleteItineraryById(itineraryId);
  console.log('Itinerary deleted successfully');
};